unit ProjectDialogUnit;

{$mode objfpc}{$H+}
{$codepage utf8}

interface

uses
  Classes, SysUtils, Forms, Controls, StdCtrls, ExtCtrls, Dialogs, Graphics,
  FileUtil;

type
  TProjectDialogResult = record
    Confirmed:      Boolean;
    Title:          string;
    Subtitle:       string;
    Author:         string;
    FolderPath:     string;  // vollständig: Hauptordner\Unterordner
    CoverImagePath: string;
  end;

  TProjectDialogForm = class(TForm)
  published
    AuthorEdit:             TEdit;
    CancelButton:           TButton;
    CoverBrowseButton:      TButton;
    CoverEdit:              TEdit;
    ErrorLabel:             TLabel;
    RootChangeBrowseButton: TButton;
    HeaderLabel:            TLabel;
    OkButton:               TButton;
    AuthorLabel:            TLabel;
    CoverLabel:             TLabel;
    RootFolderHeaderLabel:  TLabel;
    RootFolderLabel:        TLabel;
    SubfolderLabel:         TLabel;
    SubfolderEdit:          TEdit;
    PathPreviewLabel:       TLabel;
    SubtitleLabel:          TLabel;
    TitleLabel:             TLabel;
    MainPanel:              TPanel;
    SubtitleEdit:           TEdit;
    TitleEdit:              TEdit;
    procedure BrowseCoverClick(Sender: TObject);
    procedure BrowseRootFolderClick(Sender: TObject);
    procedure TitleEditChange(Sender: TObject);
    procedure SubfolderEditChange(Sender: TObject);
  private
    FRootFolder:             string;
    FSubfolderAutoGenerated: Boolean;
    function  MakeSafeSubfolder(const ATitle: string): string;
    procedure UpdatePathPreview;
    function  ValidateInput: Boolean;
  public
    function Execute(const ARootFolder: string;
                     out AResult: TProjectDialogResult): Boolean;
  end;

function ExecuteProjectDialog(const ARootFolder: string): TProjectDialogResult;

implementation

{$R *.lfm}

function TProjectDialogForm.MakeSafeSubfolder(const ATitle: string): string;
const
  FROM_CHARS: array[0..7] of string = ('ä','ö','ü','Ä','Ö','Ü','ß','·');
  TO_CHARS:   array[0..7] of string = ('ae','oe','ue','Ae','Oe','Ue','ss','_');
var
  S: string;
  I: Integer;
begin
  S := Trim(ATitle);
  for I := Low(FROM_CHARS) to High(FROM_CHARS) do
    S := StringReplace(S, FROM_CHARS[I], TO_CHARS[I], [rfReplaceAll]);
  Result := '';
  for I := 1 to Length(S) do
  begin
    if S[I] in ['A'..'Z','a'..'z','0'..'9','-','.'] then
      Result := Result + S[I]
    else if (Result <> '') and (Result[Length(Result)] <> '_') then
      Result := Result + '_';
  end;
  while (Result <> '') and (Result[Length(Result)] = '_') do
    SetLength(Result, Length(Result) - 1);
  if Result = '' then Result := 'Neues_Projekt';
end;

procedure TProjectDialogForm.UpdatePathPreview;
var
  Sub: string;
begin
  Sub := Trim(SubfolderEdit.Text);
  if (FRootFolder = '') and (Sub = '') then
    PathPreviewLabel.Caption := ''
  else if Sub = '' then
    PathPreviewLabel.Caption := FRootFolder
  else
    PathPreviewLabel.Caption :=
      IncludeTrailingPathDelimiter(FRootFolder) + Sub;
end;

procedure TProjectDialogForm.TitleEditChange(Sender: TObject);
begin
  if FSubfolderAutoGenerated then
  begin
    SubfolderEdit.Text := MakeSafeSubfolder(TitleEdit.Text);
    UpdatePathPreview;
  end;
end;

procedure TProjectDialogForm.SubfolderEditChange(Sender: TObject);
begin
  FSubfolderAutoGenerated := False;
  UpdatePathPreview;
end;

procedure TProjectDialogForm.BrowseRootFolderClick(Sender: TObject);
var
  Dir: string;
begin
  Dir := FRootFolder;
  if SelectDirectory('Hauptordner für Buchprojekte wählen', '', Dir) then
  begin
    FRootFolder := Dir;
    RootFolderLabel.Caption := Dir;
    UpdatePathPreview;
  end;
end;

procedure TProjectDialogForm.BrowseCoverClick(Sender: TObject);
var
  Dialog: TOpenDialog;
begin
  Dialog := TOpenDialog.Create(Self);
  try
    Dialog.Filter := 'Bilddateien|*.png;*.jpg;*.jpeg;*.bmp';
    if Dialog.Execute then
      CoverEdit.Text := Dialog.FileName;
  finally
    Dialog.Free;
  end;
end;

function TProjectDialogForm.ValidateInput: Boolean;
var
  FullPath: string;
begin
  ErrorLabel.Caption := '';
  Result := False;
  if Trim(TitleEdit.Text) = '' then
  begin
    ErrorLabel.Caption := 'Bitte einen Projekttitel eingeben.';
    Exit;
  end;
  if Trim(SubfolderEdit.Text) = '' then
  begin
    ErrorLabel.Caption := 'Bitte einen Unterordner-Namen eingeben.';
    Exit;
  end;
  if FRootFolder = '' then
  begin
    ErrorLabel.Caption := 'Bitte einen Hauptordner wählen.';
    Exit;
  end;
  FullPath := IncludeTrailingPathDelimiter(FRootFolder) + Trim(SubfolderEdit.Text);
  if FileExists(IncludeTrailingPathDelimiter(FullPath) + 'structura.json') then
    if MessageDlg(
      'Im Unterordner "' + Trim(SubfolderEdit.Text) +
      '" existiert bereits ein Structura-Projekt.' + LineEnding + LineEnding +
      'Trotzdem anlegen und überschreiben?',
      mtConfirmation, [mbYes, mbNo], 0) <> mrYes then
      Exit;
  Result := True;
end;

function TProjectDialogForm.Execute(const ARootFolder: string;
  out AResult: TProjectDialogResult): Boolean;
begin
  FillChar(AResult, SizeOf(AResult), 0);
  FRootFolder             := ARootFolder;
  FSubfolderAutoGenerated := True;
  RootFolderLabel.Caption := FRootFolder;
  UpdatePathPreview;
  repeat
    Result := ShowModal = mrOk;
    if not Result then Exit(False);
  until ValidateInput;
  AResult.Confirmed      := True;
  AResult.Title          := Trim(TitleEdit.Text);
  AResult.Subtitle       := Trim(SubtitleEdit.Text);
  AResult.Author         := Trim(AuthorEdit.Text);
  AResult.FolderPath     := IncludeTrailingPathDelimiter(FRootFolder)
                            + Trim(SubfolderEdit.Text);
  AResult.CoverImagePath := Trim(CoverEdit.Text);
end;

function ExecuteProjectDialog(const ARootFolder: string): TProjectDialogResult;
var
  Dialog: TProjectDialogForm;
begin
  FillChar(Result, SizeOf(Result), 0);
  Dialog := TProjectDialogForm.Create(nil);
  try
    Dialog.Execute(ARootFolder, Result);
  finally
    Dialog.Free;
  end;
end;

end.
